### ISSUE TITLE
Unhandled System.TypeInitializationException

### ISSUE THREAD

**Issue by EddyLuten** [proc-gen/roguelite-survivor#79]
Hi, I've run into an issue when attempting to run the current state of the game's repo on Ubuntu Ubuntu 22.04.2 LTS with .NET Core 7.0.203:

```
System.TypeInitializationException: The type initializer for 'Arch.Core.Utils.Group`1' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Arch.Core.Utils.Component`1' threw an exception.
 ---> System.ArgumentException: Type 'RogueliteSurvivor.Components.LoopSound' cannot be marshaled as an unmanaged structure; no meaningful size or offset can be computed.
   at System.Runtime.InteropServices.Marshal.SizeOfHelper(Type t, Boolean throwIfNotMarshalable)
   at Arch.Core.Utils.Component`1..cctor()
   --- End of inner exception stack trace ---
   at Arch.Core.Utils.Group`1..cctor()
   --- End of inner exception stack trace ---
   at RogueliteSurvivor.Scenes.GameScene..ctor(SpriteBatch spriteBatch, ContentManager contentManager, GraphicsDeviceManager graphics, Dictionary`2 playerContainers, Dictionary`2 mapContainers, ProgressionContainer progressionContainer, Dictionary`2 enemyContainers, SettingsContainer settingsContainer) in /home/eddy/code/roguelite-survivor/RogueliteSurvivor/RogueliteSurvivor/Scenes/GameScene.cs:line 56
   at RogueliteSurvivor.Game1.LoadContent() in /home/eddy/code/roguelite-survivor/RogueliteSurvivor/RogueliteSurvivor/Game1.cs:line 67
   at Microsoft.Xna.Framework.Game.Initialize()
   at RogueliteSurvivor.Game1.Initialize() in /home/eddy/code/roguelite-survivor/RogueliteSurvivor/RogueliteSurvivor/Game1.cs:line 54
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Program.<Main>$(String[] args) in /home/eddy/code/roguelite-survivor/RogueliteSurvivor/RogueliteSurvivor/Program.cs:line 8
```
I am unsure what could be causing this, but it seems to be caused by instantiating an Arch `QueryDescription` in GameScene. I set a breakpoint in the constructor, but the Exception is thrown when the class members are initialized. Upgrading Arch to the latest version (1.2.5) also did not fix the issue. Here's some system info in case that helps:

- 13th Gen Intel® Core™ i9-13900KF × 32
- Mesa Intel® Arc(tm) A770 Graphics (DG2)
- Ubuntu 22.04.2 LTS using Wayland
- 64 GB RAM

**Comment by proc-gen** [comment]
I should've known better than to cause one of these issues again...

You should be able to change `LoopSound` from a struct to a class to make it work. I ran into this early on with the `MapInfo` component when someone was testing for me on their Mac.

For whatever reason, Windows doesn't seem to care when a struct contains class fields, but Mac and Linux both catch the error.

**Comment by EddyLuten** [comment]
> You should be able to change LoopSound from a struct to a class to make it work. I ran into this early on with the MapInfo component when someone was testing for me on their Mac.

Yup, this did the trick! After making this change, the game launched just fine.
